# This is a basic workflow to help you get started with Actions

name: CD

on:
  pull_request:
    branches: [ source ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: GIT_USER=$GIT_USER yarn deploy
      env:
        GIT_USER: tpilvelis-gw
